if __name__ == "__main__":
    orgs_2017 = ['52°North Initiative for Geospatial Open Source Software GmbH',
                 'AboutCode',
                 'AerospaceResearch.net',
                 'aimacode',
                 'Amahi',
                 'AOSSIE - Australian Open Source Software Innovation and Education',
                 'Apache Software Foundation',
                 'Apertium',
                 'Apertus Association',
                 'appleseedhq',
                 'ArduPilot',
                 'Babel',
                 'Bazel',
                 'BeagleBoard.org Foundation',
                 'Beam Community',
                 'BeeWare Project',
                 'Berkman Klein Center for Internet and Society at Harvard University',
                 'Blender Foundation',
                 'Boost C++ Libraries',
                 'Boston University / XIA',
                 'BRL-CAD',
                 'Cadasta',
                 'Catrobat',
                 'cBioPortal for Cancer Genomics',
                 'CCExtractor Development',
                 'Ceph',
                 'CERN-HSF',
                 'Chapel',
                 'Checker Framework',
                 'Checkstyle',
                 'Classical Language Toolkit',
                 'CLiPS',
                 'University of Antwerp',
                 'Clojure',
                 'Cloud Native Computing Foundation (CNCF)',
                 'CloudCV',
                 'CMU Sphinx',
                 'coala',
                 'Computational Biology @ University of Nebraska-Lincoln',
                 'Conversations.im',
                 'Copyleft Games',
                 'DBpedia',
                 'Discourse',
                 'Django Software Foundation',
                 'Drupal',
                 'Eclipse Vert.x',
                 'Elm Software Foundation',
                 'Environmental Data And Governance Initiative',
                 'Fedora Project',
                 'FFmpeg',
                 'FOSDEM',
                 'FOSSASIA',
                 'Free and Open Source Silicon Foundation',
                 'FreeBSD',
                 'Freifunk',
                 'Frescobaldi',
                 'Genes',
                 'Genomes and Variation',
                 'GENIVI Development Platform',
                 'Gentoo Foundation',
                 'Git',
                 'Global Alliance for Genomics and Health',
                 'GNOME',
                 'GNSS-SDR',
                 'GNU Octave',
                 'GNU Radio',
                 'Green Navigation',
                 'Haiku',
                 'Homebrew',
                 'illumos.org',
                 'INCF',
                 'Inkscape',
                 'Institute for Artificial Intelligence',
                 'Intel Media and Audio for Linux',
                 'Internet Archive',
                 'JBoss Community',
                 'JdeRobot - Universidad Rey Juan Carlos',
                 'Jitsi',
                 'Joomla',
                 'JSK Robotics Laboratory',
                 'K-9 Mail',
                 'KDE',
                 'LabLua',
                 'LibreHealth',
                 'LibreOffice',
                 'libvirt',
                 'Liquid Galaxy Project',
                 'LLVM Compiler Infrastructure',
                 'lowRISC',
                 'LuaRocks',
                 'MariaDB',
                 'Matrix.org',
                 'MBDyn',
                 'MetaBrainz Foundation Inc.',
                 'Metasploit',
                 'Microkernel devroom',
                 'Mifos Initiative',
                 'MIT App Inventor',
                 'Mixxx DJ Software',
                 'mlpack',
                 'Mobile Robot Programming Toolkit (MRPT)',
                 'Mono Project',
                 'Moodle',
                 'MovingBlocks',
                 'Mozilla',
                 'MuseScore',
                 'National Resource for Network Biology (NRNB)',
                 'Netfilter project',
                 'Nmap Security Scanner',
                 'NumFOCUS',
                 'Open Bioinformatics Foundation',
                 'Open Chemistry',
                 'Open Data Kit',
                 'Open Detection',
                 'Open Genome Informatics',
                 'Open States',
                 'Open Technologies Alliance - GFOSS',
                 'OpenAstronomy',
                 'OpenCV',
                 'OpenMRS',
                 'OpenStreetMap',
                 'openSUSE',
                 'OpenWISP',
                 'Oppia Foundation',
                 'OSGeo',
                 'oVirt',
                 'ownCloud',
                 'P2PSP.org',
                 'PEcAn Project',
                 'Performance Co-Pilot',
                 'Pharo Consortium',
                 'phpBB Forum Software',
                 'phpMyAdmin',
                 'Physical Web Project',
                 'Plone Foundation',
                 'PMD',
                 'Polly Labs',
                 'Portland State University',
                 'PostgreSQL',
                 'Public Lab',
                 'Python Software Foundation',
                 'QEMU',
                 'Qubes OS',
                 'R project for statistical computing',
                 'radare2',
                 'ReactOS',
                 'Red Hen Lab',
                 'RoboComp',
                 'Rocket.Chat',
                 'Rspamd',
                 'RTEMS Project',
                 'Ruby on Rails',
                 'Ruby Science Foundation',
                 'Sage Mathematical Software System',
                 'Samba',
                 'Scala',
                 'Scilab',
                 'ScummVM',
                 'Shogun Machine Learning Toolbox',
                 'Sigmah',
                 'Software Product Data Exchange (SPDX)',
                 'STE||AR Group',
                 'Stony Brook University',
                 'Biomedical Informatics',
                 'strace',
                 'Sugar Labs',
                 'Sustainable Computing Research Group ( SCoRe )',
                 'SymPy',
                 'Systers',
                 'an Anita Borg Institute community',
                 'TEAMMATES @ National University of Singapore',
                 'The Center for Connected Learning and Computer-Based Modeling',
                 'The CGAL Project',
                 'The Eclipse Foundation',
                 'The FreeType Project',
                 'The GNU Project',
                 'The Honeynet Project',
                 'The Java Pathfinder Team',
                 'The Julia Language',
                 'The Libreswan Project',
                 'The Linux Foundation',
                 'The MacPorts Project',
                 'The NetBSD Foundation',
                 'The ns-3 Network Simulator Project',
                 'The Processing Foundation',
                 'The Wine Project',
                 'Tiled',
                 'TimVideos',
                 'Tor',
                 'UCSC Xena',
                 'Urban Energy Systems Laboratory',
                 'Empa',
                 'VideoLAN',
                 'ViSP',
                 'Wikimedia Foundation',
                 'WorldBrain - Verifying the Internet with Science',
                 'WSO2',
                 'wxWidgets',
                 'X.Org Foundation',
                 'Xapian Search Engine Library',
                 'XBMC Foundation',
                 'Xen Project',
                 'XMPP Standards Foundation',
                 'XWiki',
                 'Zenodo',
                 'Zulip']
    orgs_2016 = ['52°North Initiative for Geospatial Open Source Software GmbH',
                 'aimacode',
                 "AOSSIE - The Australian National University's Open-Source Software "
                 'Innovation and Education',
                 'Apache Software Foundation',
                 'ArchC',
                 'ASCEND',
                 'BeagleBoard.org',
                 'Beam Community',
                 'Berkman Center for Internet and Society',
                 'BioJS',
                 'Biomedical Informatics',
                 'Emory University',
                 'Blender Foundation',
                 'Boston University / XIA',
                 'BRL-CAD',
                 'BuildmLearn',
                 'Canadian Centre for Computational Genomics (C3G) - Montreal node',
                 'Catrobat',
                 'cBioPortal for Cancer Genomics',
                 'CCExtractor Development',
                 'Celluloid',
                 'Ceph',
                 'CERN SFT',
                 'Chapel',
                 'CiviCRM',
                 'Classical Language Toolkit',
                 'CloudCV',
                 'Computational Biology @ University of Nebraska-Lincoln',
                 'Computational Science and Engineering at TU Wien',
                 'Copyleft Games',
                 'coreboot',
                 'CVXPY',
                 'D Foundation',
                 'dbpediaspotlight',
                 'Debian Project',
                 'Discourse',
                 'Distributed and Unified Numerics Environment (DUNE)',
                 'Django Software Foundation',
                 'Drupal',
                 'Eclipse Foundation',
                 'Fedora Project',
                 'FFmpeg',
                 'FOSDEM VZW',
                 'FOSSASIA',
                 'Free and Open Source Silicon Foundation',
                 'FreeBSD',
                 'Freifunk',
                 'Gambit - Software Tools for Game Theory',
                 'Ganeti',
                 'Genes',
                 'Genomes and Variation',
                 'Gentoo Foundation',
                 'Git',
                 'GitHub',
                 'Global Alliance for Genomics & Health',
                 'GNOME',
                 'gnss-sdr',
                 'GNU Mailman',
                 'GNU Octave',
                 'GNU Project',
                 'GNU Radio',
                 'GPAC',
                 'Green Navigation',
                 'gRPC',
                 'Health Information Systems Programme',
                 'Homebrew',
                 'Inclusive Design Institute',
                 'Indic Project',
                 'Inkscape',
                 'International Neuroinformatics Coordinating Facility',
                 'Java Pathfinder Team',
                 'JBoss Community',
                 'Jenkins Project',
                 'Joomla!',
                 'jQuery Foundation',
                 'JSK Robotics Laboratory',
                 'KDE',
                 'KolibriOS',
                 'LabLua',
                 'LibreOffice',
                 'Libvirt',
                 'Liquid Galaxy Project',
                 'lowRISC',
                 'MariaDB',
                 'Matrix.org',
                 'MBDyn',
                 'Department of Aerospace Science and Technology at Politecnico di Milano',
                 'McGill Space Institute',
                 'MetaBrainz Foundation',
                 'Mifos Initiative',
                 'MIT Media Lab',
                 'Mixxx DJ Software',
                 'mlpack: a scalable C++ machine learning library',
                 'Mobile Robot Programming Toolkit (MRPT)',
                 'ModSecurity',
                 'Moodle',
                 'MovingBlocks',
                 'Mozilla',
                 'MuseScore',
                 'National Resource for Network Biology (NRNB)',
                 'Netfilter project',
                 'Nmap Security Scanner',
                 'NumFOCUS',
                 'Open Bioinformatics Foundation',
                 'Open Chemistry',
                 'Open Detection',
                 'Open Ephys',
                 'Open Genome Informatics',
                 'Open Source Robotics Foundation',
                 'OpenAstronomy',
                 'OpenCV',
                 'OpenKeychain (OpenPGP for Android)',
                 'OpenMRS',
                 'OpenStreetMap',
                 'openSUSE',
                 'Oppia Foundation',
                 'Orange – Data Mining Fruitful & Fun',
                 'OSGeo - The Open Source Geospatial Foundation',
                 'OSU Open Source Lab',
                 'OWASP Foundation',
                 'ownCloud',
                 'P2PSP.org',
                 'Peragro',
                 'Performance Co-Pilot',
                 'Physical Web Project',
                 'PLASMA-UMass',
                 'Plone Foundation',
                 'Portland State University',
                 'PRISM Model Checker',
                 'Public Lab',
                 'Python Software Foundation',
                 'QEMU',
                 'R project for statistical computing',
                 'radare',
                 'ReactOS',
                 'Red Hen Lab',
                 'Robocomp',
                 'RTEMS Project',
                 'Ruby',
                 'Ruby Science Foundation',
                 'Sage Mathematical Software System',
                 'Scala',
                 'Scilab Enterprises',
                 'ScummVM',
                 'Shogun Machine Learning Toolbox',
                 'Sigmah',
                 'Soletta Project',
                 'Stony Brook University Biomedical Informatics',
                 'strace',
                 'Sugar Labs',
                 'Sustainable Computing Research Group ( SCoRe )',
                 'SymPy',
                 'Systers',
                 'an Anita Borg Institute Community',
                 'TARDIS-SN',
                 'TEAMMATES @ National University of Singapore',
                 'The Apertium Project',
                 'The Center for Connected Learning and Computer-Based Modeling',
                 'The Honeynet Project',
                 'The Julia Language',
                 'The Linux Foundation',
                 'The LLVM Compiler Infrastructure',
                 'The Monarch Initiative',
                 'The NetBSD Foundation',
                 'The STE||AR Group',
                 'The syslog-ng project',
                 'The Tor Project',
                 'The Wine Project',
                 'Timelab Technologies Ltd.',
                 'TimVideos.us',
                 'Unitex/GramLab',
                 'Urban Energy Systems Laboratory',
                 'Empa',
                 'Vert.x',
                 'VideoLAN / VLMC Project',
                 'vitrivr',
                 'Wayland',
                 'Wikimedia Foundation',
                 'WSO2',
                 'X.Org Foundation',
                 'Xapian Search Engine Library',
                 'XWiki',
                 'Zulip Open Source Project']
    orgs_2015 = ['52°North Initiative for Geospatial Open Source Software GmbH',
                 'Africa Soil Information Service',
                 'Apache Software Foundation',
                 'ASCEND',
                 'BeagleBoard.org',
                 'BEAM Community',
                 'Bika Open Source LIMS Collective',
                 'Biomedical Informatics',
                 ' Emory University',
                 'Boost C++ Libraries',
                 'Boston University / XIA',
                 'BRL-CAD',
                 'Buildbot',
                 'BuildmLearn',
                 'CCExtractor development',
                 'CentOS Project',
                 'Ceph Storage',
                 'CERN SFT',
                 'Cesium Community',
                 'CiviCRM',
                 'Clojure',
                 'CloudCV',
                 'Copyleft Games',
                 'coreboot',
                 'DBpedia & DBpedia Spotlight',
                 'Debian Project',
                 'Department of Biomedical Informatics',
                 ' Stony Brook University',
                 'Drupal',
                 'Encyclopedia of Life',
                 'FFmpeg',
                 'FOSSASIA',
                 'Foundation for Learning Equality',
                 'FreeBSD',
                 'Ganeti',
                 'GCC - GNU Compiler Collection',
                 'Git',
                 'GitHub',
                 'Global Alliance for Genomics & Health',
                 'GNOME',
                 'GNSS-SDR',
                 'GNU Mailman',
                 'GNU Project',
                 'Google Kubernetes',
                 'haskell.org',
                 'HPCC Systems®',
                 'Institute for Artificial Intelligence',
                 'Interactive Spaces',
                 'International GeoGebra Institute',
                 'International Neuroinformatics Coordinating Facility',
                 'IP-over-P2P Project',
                 'JBoss Community',
                 'JdeRobot - Universidad Rey Juan Carlos',
                 'jQuery Foundation',
                 'KDE',
                 'LabLua',
                 'LibreOffice',
                 'Liquid Galaxy Project',
                 'LLVM Compiler Infrastructure',
                 'lmonade: scientific software distribution',
                 'lowRISC',
                 'MariaDB',
                 'MBDyn',
                 ' Department of Aerospace Engineering at the Polytechnic University of Milan',
                 'MEDES-IMPS',
                 'MetaBrainz Foundation Inc.',
                 'MinnowBoard Project',
                 'MIT Media Lab',
                 'Mono Project',
                 'Moodle',
                 'Network Time Foundation',
                 'Nmap Security Scanner',
                 'NumFOCUS',
                 'OncoBlocks',
                 'Open Source Computer Vision Library (OpenCV)',
                 'Open Source Robotics Foundation',
                 'OpenKeychain (OpenPGP for Android)',
                 'OpenMRS',
                 'OpenStreetMap',
                 'Openwall',
                 'Oregon State University Open Source Lab (OSUOSL)',
                 'OSGeo - Open Source Geospatial Foundation',
                 'P2PSP.org',
                 'PaGMO / PyKEP',
                 'Pencil Code Foundation',
                 'phpMyAdmin',
                 'Pidgin',
                 ' Finch',
                 ' and libpurple',
                 'PLASMA @ UMass',
                 'Portable Native Client',
                 'Portland State University',
                 'PostgreSQL Project',
                 'Privly Foundation',
                 'Python Software Foundation',
                 'QEMU',
                 'R Project for Statistical Computing',
                 'Red Hen Lab',
                 'RIOT',
                 'RoboComp',
                 'RouteFlow',
                 'Rspamd spam filtering system',
                 'RTEMS Project',
                 'Ruby',
                 'Ruby on Rails',
                 'Ruby Science Foundation',
                 'Sage Mathematical Software System',
                 'Saros',
                 'Scala Team',
                 'Scilab Enterprises',
                 'strace',
                 'Subsurface',
                 'Sugar Labs',
                 'Sustainable Computing Research Group ( SCoRe )',
                 'Systers',
                 ' an Anita Borg Institute Community',
                 'TARDIS SN',
                 'TEAMMATES @ National University of Singapore',
                 'The Concord Consortium',
                 'The Eclipse Foundation',
                 'The Fedora Project',
                 'The Honeynet Project',
                 'The MacPorts Project',
                 'The ns-3 Network Simulator Project',
                 'The OpenBSD Foundation',
                 'The OpenCog Foundation',
                 'The Processing Foundation',
                 'The STE||AR Group',
                 'The syslog-ng project',
                 'The Visualization Toolkit',
                 'The Wine Project',
                 'Tox',
                 'Tux4Kids',
                 'University of Nebraska - Helikar Lab',
                 'Wikimedia Foundation',
                 'WSO2',
                 'X.Org Foundation',
                 'XBMC Foundation',
                 'Xiph.Org Foundation',
                 'XMPP Standards Foundation']
    orgs_2014 = ['52°North Initiative for Geospatial Open Source Software GmbH',
                 'AerospaceResearch.Net',
                 'Amahi',
                 'Apache Software Foundation',
                 'Apertium',
                 'appleseed',
                 'Arches Project',
                 'Association Tatoeba',
                 'Battle for Wesnoth',
                 'BeagleBoard.org',
                 'BEAM Community',
                 'Benetech',
                 'Bio4j',
                 'BioJavaScript',
                 'Biomedical Informatics',
                 ' Emory University',
                 'Blender Foundation',
                 'Bookie',
                 'Boost C++ Libraries',
                 'BRL-CAD',
                 'Buildbot',
                 'BuildmLearn',
                 'BumbleBee Autonomous Underwater Vehicle (BBAUV)',
                 'Catrobat (formerly Catroid Project)',
                 'CCExtractor development',
                 'Centre for Computational Medicine',
                 ' SickKids Research Institute',
                 'Ceph',
                 'CERN SFT',
                 'Checkstyle',
                 'CiviCRM',
                 'Clojure',
                 'CodeCombat',
                 'CodeMirror',
                 'Computational Science and Engineering at TU Wien',
                 'Copyleft Games',
                 'coreboot',
                 'Crypto Stick',
                 'Crystal Space',
                 'DBpedia & DBpedia Spotlight',
                 'Debian Project',
                 'Django Software Foundation',
                 'Dr. Memory',
                 'Drupal',
                 'Flowgrammable',
                 'FOSSASIA',
                 'FreeBSD',
                 'Freenet Project Inc',
                 'Freifunk',
                 'Frenetic',
                 'Gambit: Software Tools for Game Theory',
                 'Ganeti',
                 'Ganglia',
                 'GCC - GNU Compiler Collection',
                 'Gentoo Foundation',
                 'Git',
                 'GNOME',
                 'GNSS-SDR',
                 'GNU Octave',
                 'GNU Project',
                 'GNU Radio',
                 'Google Open Source Programs Office',
                 'Grameen Foundation - MOTECH',
                 'Groovy Community',
                 'Haiku',
                 'haskell.org',
                 'Health Information Systems Programme',
                 'HelenOS group at Department of Distributed and Dependable Systems',
                 ' Charles University in Prague',
                 'Inclusive Design Institute',
                 'Inkscape',
                 'Institute for Artificial Intelligence',
                 'International Neuroinformatics Coordinating Facility',
                 'Italian Mars Society',
                 'JBoss Community',
                 'Jitsi',
                 'jMonkeyEngine',
                 'Joomla! (Open Source Matters)',
                 'KDE',
                 'KolibriOS Project Team',
                 'LabLua',
                 'Laboratory for Cosmological Data Mining',
                 'LEAP Encryption Access Project',
                 'LibreOffice',
                 'Linaro',
                 'Linux Trace Toolkit next generation project (LTTng)',
                 'Liquid Galaxy Project',
                 'LLVM Compiler Infrastructure',
                 'lmonade: scientific software distribution',
                 'LyX – The Document Processor',
                 'MariaDB',
                 'Melange',
                 'MetaBrainz Foundation Inc.',
                 'Mifos Initiative',
                 'Mixxx DJ Software',
                 'mlpack: scalable C++ machine learning library',
                 'Monkey Project',
                 'Mono Project',
                 'Moodle',
                 'Mozilla',
                 'MuseScore',
                 'National Resource for Network Biology (NRNB)',
                 'Netfilter Project',
                 'NetSurf',
                 'Nmap Security Scanner',
                 'OGDF - Open Graph Drawing Framework',
                 'Open Bioinformatics Foundation',
                 'Open Education Resource Foundation',
                 'Open Lighting Project',
                 'Open Motion Planning Library',
                 'Open Source Computer Vision Library (OpenCV)',
                 'Open Source Robotics Foundation',
                 'OpenKeychain (OpenPGP for Android)',
                 'OpenMRS',
                 'openSUSE',
                 'Oregon State University Open Source Lab (OSUOSL)',
                 'OSGeo - Open Source Geospatial Foundation',
                 'OSv',
                 'oVirt',
                 'OWASP Foundation',
                 'phpBB Forum Software',
                 'phpMyAdmin',
                 'Plan 9 from Bell Labs',
                 'Plone Foundation',
                 'Point Cloud Library (PCL)',
                 'Portland State University',
                 'PostgreSQL Project',
                 'PRISM Model Checker',
                 'Project Tox',
                 'Public Laboratory for Open Technology and Science',
                 'Python Software Foundation',
                 'QEMU',
                 'R Project for Statistical Computing',
                 'Raxa',
                 'RouteFlow',
                 'RTEMS Project',
                 'Ruby on Rails',
                 'Ruby Science Foundation (SciRuby)',
                 'Sage Mathematical Software System',
                 'Sahana Software Foundation',
                 'Samba',
                 'Scaffold Hunter',
                 'Scala Team',
                 'ScummVM',
                 'Shogun Machine Learning Toolbox',
                 'Sigmah',
                 'Software Freedom Conservancy',
                 ' Inc.',
                 'Steel Bank Common Lisp',
                 'strace',
                 'Stratosphere Project',
                 'Subsurface',
                 'Sugar Labs',
                 'SuperTuxKart',
                 'Swathanthra Malayalam Computing',
                 'SymPy',
                 'SyncDiff(erent)',
                 'Systers',
                 ' an Anita Borg Institute Community',
                 'TEAMMATES Project @ National University of Singapore',
                 'The CGAL Project',
                 'The Concord Consortium',
                 'The Eclipse Foundation',
                 'The Fedora Project',
                 'The Julia Language',
                 'The Linux Foundation',
                 'The MacPorts Project',
                 'The ns-3 Network Simulator Project',
                 'The OpenBSD Foundation',
                 'The OpenCog Foundation',
                 'The OpenStack Foundation',
                 'The Perl Foundation',
                 'The Privly Foundation',
                 'The Processing Foundation',
                 'The STE||AR Group',
                 'The syslog-ng project',
                 'The Tor Project and EFF',
                 'The Wine Project',
                 'The Wiselib',
                 'ThinkUp',
                 'TimVideos.us',
                 'Twitter',
                 'TYPO3 Association',
                 'Visualization Toolkit (VTK)',
                 'Wikimedia',
                 'WordPress',
                 'WorldForge',
                 'WSO2',
                 'wxWidgets',
                 'X.Org Foundation',
                 'Xapian Search Engine Library',
                 'Xen Project']
    orgs = {' Charles University in Prague': [2014],
            ' Department of Aerospace Engineering at the Polytechnic University of Milan': [2015],
            ' Emory University': [2015, 2014],
            ' Finch': [2015],
            ' Inc.': [2014],
            ' SickKids Research Institute': [2014],
            ' Stony Brook University': [2015],
            ' an Anita Borg Institute Community': [2015, 2014],
            ' and libpurple': [2015],
            '52°North Initiative for Geospatial Open Source Software GmbH': [2017, 2016, 2015, 2014],
            'AOSSIE - Australian Open Source Software Innovation and Education': [2017],
            "AOSSIE - The Australian National University's Open-Source Software Innovation and Education": [2016],
            'ASCEND': [2016, 2015],
            'AboutCode': [2017],
            'AerospaceResearch.Net': [2014],
            'AerospaceResearch.net': [2017],
            'Africa Soil Information Service': [2015],
            'Amahi': [2017, 2014],
            'Apache Software Foundation': [2017, 2016, 2015, 2014],
            'Apertium': [2017, 2014],
            'Apertus Association': [2017],
            'ArchC': [2016],
            'Arches Project': [2014],
            'ArduPilot': [2017],
            'Association Tatoeba': [2014],
            'BEAM Community': [2015, 2014],
            'BRL-CAD': [2017, 2016, 2015, 2014],
            'Babel': [2017],
            'Battle for Wesnoth': [2014],
            'Bazel': [2017],
            'BeagleBoard.org': [2016, 2015, 2014],
            'BeagleBoard.org Foundation': [2017],
            'Beam Community': [2017, 2016],
            'BeeWare Project': [2017],
            'Benetech': [2014],
            'Berkman Center for Internet and Society': [2016],
            'Berkman Klein Center for Internet and Society at Harvard University': [2017],
            'Bika Open Source LIMS Collective': [2015],
            'Bio4j': [2014],
            'BioJS': [2016],
            'BioJavaScript': [2014],
            'Biomedical Informatics': [2017, 2016, 2015, 2014],
            'Blender Foundation': [2017, 2016, 2014],
            'Bookie': [2014],
            'Boost C++ Libraries': [2017, 2015, 2014],
            'Boston University / XIA': [2017, 2016, 2015],
            'Buildbot': [2015, 2014],
            'BuildmLearn': [2016, 2015, 2014],
            'BumbleBee Autonomous Underwater Vehicle (BBAUV)': [2014],
            'CCExtractor Development': [2017, 2016],
            'CCExtractor development': [2015, 2014],
            'CERN SFT': [2016, 2015, 2014],
            'CERN-HSF': [2017],
            'CLiPS': [2017],
            'CMU Sphinx': [2017],
            'CVXPY': [2016],
            'Cadasta': [2017],
            'Canadian Centre for Computational Genomics (C3G) - Montreal node': [2016],
            'Catrobat': [2017, 2016],
            'Catrobat (formerly Catroid Project)': [2014],
            'Celluloid': [2016],
            'CentOS Project': [2015],
            'Centre for Computational Medicine': [2014],
            'Ceph': [2017, 2016, 2014],
            'Ceph Storage': [2015],
            'Cesium Community': [2015],
            'Chapel': [2017, 2016],
            'Checker Framework': [2017],
            'Checkstyle': [2017, 2014],
            'CiviCRM': [2016, 2015, 2014],
            'Classical Language Toolkit': [2017, 2016],
            'Clojure': [2017, 2015, 2014],
            'Cloud Native Computing Foundation (CNCF)': [2017],
            'CloudCV': [2017, 2016, 2015],
            'CodeCombat': [2014],
            'CodeMirror': [2014],
            'Computational Biology @ University of Nebraska-Lincoln': [2017, 2016],
            'Computational Science and Engineering at TU Wien': [2016, 2014],
            'Conversations.im': [2017],
            'Copyleft Games': [2017, 2016, 2015, 2014],
            'Crypto Stick': [2014],
            'Crystal Space': [2014],
            'D Foundation': [2016],
            'DBpedia': [2017],
            'DBpedia & DBpedia Spotlight': [2015, 2014],
            'Debian Project': [2016, 2015, 2014],
            'Department of Aerospace Science and Technology at Politecnico di Milano': [2016],
            'Department of Biomedical Informatics': [2015],
            'Discourse': [2017, 2016],
            'Distributed and Unified Numerics Environment (DUNE)': [2016],
            'Django Software Foundation': [2017, 2016, 2014],
            'Dr. Memory': [2014],
            'Drupal': [2017, 2016, 2015, 2014],
            'Eclipse Foundation': [2016],
            'Eclipse Vert.x': [2017],
            'Elm Software Foundation': [2017],
            'Emory University': [2016],
            'Empa': [2017, 2016],
            'Encyclopedia of Life': [2015],
            'Environmental Data And Governance Initiative': [2017],
            'FFmpeg': [2017, 2016, 2015],
            'FOSDEM': [2017],
            'FOSDEM VZW': [2016],
            'FOSSASIA': [2017, 2016, 2015, 2014],
            'Fedora Project': [2017, 2016],
            'Flowgrammable': [2014],
            'Foundation for Learning Equality': [2015],
            'Free and Open Source Silicon Foundation': [2017, 2016],
            'FreeBSD': [2017, 2016, 2015, 2014],
            'Freenet Project Inc': [2014],
            'Freifunk': [2017, 2016, 2014],
            'Frenetic': [2014],
            'Frescobaldi': [2017],
            'GCC - GNU Compiler Collection': [2015, 2014],
            'GENIVI Development Platform': [2017],
            'GNOME': [2017, 2016, 2015, 2014],
            'GNSS-SDR': [2017, 2015, 2014],
            'GNU Mailman': [2016, 2015],
            'GNU Octave': [2017, 2016, 2014],
            'GNU Project': [2016, 2015, 2014],
            'GNU Radio': [2017, 2016, 2014],
            'GPAC': [2016],
            'Gambit - Software Tools for Game Theory': [2016],
            'Gambit: Software Tools for Game Theory': [2014],
            'Ganeti': [2016, 2015, 2014],
            'Ganglia': [2014],
            'Genes': [2017, 2016],
            'Genomes and Variation': [2017, 2016],
            'Gentoo Foundation': [2017, 2016, 2014],
            'Git': [2017, 2016, 2015, 2014],
            'GitHub': [2016, 2015],
            'Global Alliance for Genomics & Health': [2016, 2015],
            'Global Alliance for Genomics and Health': [2017],
            'Google Kubernetes': [2015],
            'Google Open Source Programs Office': [2014],
            'Grameen Foundation - MOTECH': [2014],
            'Green Navigation': [2017, 2016],
            'Groovy Community': [2014],
            'HPCC Systems®': [2015],
            'Haiku': [2017, 2014],
            'Health Information Systems Programme': [2016, 2014],
            'HelenOS group at Department of Distributed and Dependable Systems': [2014],
            'Homebrew': [2017, 2016],
            'INCF': [2017],
            'IP-over-P2P Project': [2015],
            'Inclusive Design Institute': [2016, 2014],
            'Indic Project': [2016],
            'Inkscape': [2017, 2016, 2014],
            'Institute for Artificial Intelligence': [2017, 2015, 2014],
            'Intel Media and Audio for Linux': [2017],
            'Interactive Spaces': [2015],
            'International GeoGebra Institute': [2015],
            'International Neuroinformatics Coordinating Facility': [2016, 2015, 2014],
            'Internet Archive': [2017],
            'Italian Mars Society': [2014],
            'JBoss Community': [2017, 2016, 2015, 2014],
            'JSK Robotics Laboratory': [2017, 2016],
            'Java Pathfinder Team': [2016],
            'JdeRobot - Universidad Rey Juan Carlos': [2017, 2015],
            'Jenkins Project': [2016],
            'Jitsi': [2017, 2014],
            'Joomla': [2017],
            'Joomla!': [2016],
            'Joomla! (Open Source Matters)': [2014],
            'K-9 Mail': [2017],
            'KDE': [2017, 2016, 2015, 2014],
            'KolibriOS': [2016],
            'KolibriOS Project Team': [2014],
            'LEAP Encryption Access Project': [2014],
            'LLVM Compiler Infrastructure': [2017, 2015, 2014],
            'LabLua': [2017, 2016, 2015, 2014],
            'Laboratory for Cosmological Data Mining': [2014],
            'LibreHealth': [2017],
            'LibreOffice': [2017, 2016, 2015, 2014],
            'Libvirt': [2016],
            'Linaro': [2014],
            'Linux Trace Toolkit next generation project (LTTng)': [2014],
            'Liquid Galaxy Project': [2017, 2016, 2015, 2014],
            'LuaRocks': [2017],
            'LyX – The Document Processor': [2014],
            'MBDyn': [2017, 2016, 2015],
            'MEDES-IMPS': [2015],
            'MIT App Inventor': [2017],
            'MIT Media Lab': [2016, 2015],
            'MariaDB': [2017, 2016, 2015, 2014],
            'Matrix.org': [2017, 2016],
            'McGill Space Institute': [2016],
            'Melange': [2014],
            'MetaBrainz Foundation': [2016],
            'MetaBrainz Foundation Inc.': [2017, 2015, 2014],
            'Metasploit': [2017],
            'Microkernel devroom': [2017],
            'Mifos Initiative': [2017, 2016, 2014],
            'MinnowBoard Project': [2015],
            'Mixxx DJ Software': [2017, 2016, 2014],
            'Mobile Robot Programming Toolkit (MRPT)': [2017, 2016],
            'ModSecurity': [2016],
            'Monkey Project': [2014],
            'Mono Project': [2017, 2015, 2014],
            'Moodle': [2017, 2016, 2015, 2014],
            'MovingBlocks': [2017, 2016],
            'Mozilla': [2017, 2016, 2014],
            'MuseScore': [2017, 2016, 2014],
            'National Resource for Network Biology (NRNB)': [2017, 2016, 2014],
            'NetSurf': [2014],
            'Netfilter Project': [2014],
            'Netfilter project': [2017, 2016],
            'Network Time Foundation': [2015],
            'Nmap Security Scanner': [2017, 2016, 2015, 2014],
            'NumFOCUS': [2017, 2016, 2015],
            'OGDF - Open Graph Drawing Framework': [2014],
            'OSGeo': [2017],
            'OSGeo - Open Source Geospatial Foundation': [2015, 2014],
            'OSGeo - The Open Source Geospatial Foundation': [2016],
            'OSU Open Source Lab': [2016],
            'OSv': [2014],
            'OWASP Foundation': [2016, 2014],
            'OncoBlocks': [2015],
            'Open Bioinformatics Foundation': [2017, 2016, 2014],
            'Open Chemistry': [2017, 2016],
            'Open Data Kit': [2017],
            'Open Detection': [2017, 2016],
            'Open Education Resource Foundation': [2014],
            'Open Ephys': [2016],
            'Open Genome Informatics': [2017, 2016],
            'Open Lighting Project': [2014],
            'Open Motion Planning Library': [2014],
            'Open Source Computer Vision Library (OpenCV)': [2015, 2014],
            'Open Source Robotics Foundation': [2016, 2015, 2014],
            'Open States': [2017],
            'Open Technologies Alliance - GFOSS': [2017],
            'OpenAstronomy': [2017, 2016],
            'OpenCV': [2017, 2016],
            'OpenKeychain (OpenPGP for Android)': [2016, 2015, 2014],
            'OpenMRS': [2017, 2016, 2015, 2014],
            'OpenStreetMap': [2017, 2016, 2015],
            'OpenWISP': [2017],
            'Openwall': [2015],
            'Oppia Foundation': [2017, 2016],
            'Orange – Data Mining Fruitful & Fun': [2016],
            'Oregon State University Open Source Lab (OSUOSL)': [2015, 2014],
            'P2PSP.org': [2017, 2016, 2015],
            'PEcAn Project': [2017],
            'PLASMA @ UMass': [2015],
            'PLASMA-UMass': [2016],
            'PMD': [2017],
            'PRISM Model Checker': [2016, 2014],
            'PaGMO / PyKEP': [2015],
            'Pencil Code Foundation': [2015],
            'Peragro': [2016],
            'Performance Co-Pilot': [2017, 2016],
            'Pharo Consortium': [2017],
            'Physical Web Project': [2017, 2016],
            'Pidgin': [2015],
            'Plan 9 from Bell Labs': [2014],
            'Plone Foundation': [2017, 2016, 2014],
            'Point Cloud Library (PCL)': [2014],
            'Polly Labs': [2017],
            'Portable Native Client': [2015],
            'Portland State University': [2017, 2016, 2015, 2014],
            'PostgreSQL': [2017],
            'PostgreSQL Project': [2015, 2014],
            'Privly Foundation': [2015],
            'Project Tox': [2014],
            'Public Lab': [2017, 2016],
            'Public Laboratory for Open Technology and Science': [2014],
            'Python Software Foundation': [2017, 2016, 2015, 2014],
            'QEMU': [2017, 2016, 2015, 2014],
            'Qubes OS': [2017],
            'R Project for Statistical Computing': [2015, 2014],
            'R project for statistical computing': [2017, 2016],
            'RIOT': [2015],
            'RTEMS Project': [2017, 2016, 2015, 2014],
            'Raxa': [2014],
            'ReactOS': [2017, 2016],
            'Red Hen Lab': [2017, 2016, 2015],
            'RoboComp': [2017, 2015],
            'Robocomp': [2016],
            'Rocket.Chat': [2017],
            'RouteFlow': [2015, 2014],
            'Rspamd': [2017],
            'Rspamd spam filtering system': [2015],
            'Ruby': [2016, 2015],
            'Ruby Science Foundation': [2017, 2016, 2015],
            'Ruby Science Foundation (SciRuby)': [2014],
            'Ruby on Rails': [2017, 2015, 2014],
            'STE||AR Group': [2017],
            'Sage Mathematical Software System': [2017, 2016, 2015, 2014],
            'Sahana Software Foundation': [2014],
            'Samba': [2017, 2014],
            'Saros': [2015],
            'Scaffold Hunter': [2014],
            'Scala': [2017, 2016],
            'Scala Team': [2015, 2014],
            'Scilab': [2017],
            'Scilab Enterprises': [2016, 2015],
            'ScummVM': [2017, 2016, 2014],
            'Shogun Machine Learning Toolbox': [2017, 2016, 2014],
            'Sigmah': [2017, 2016, 2014],
            'Software Freedom Conservancy': [2014],
            'Software Product Data Exchange (SPDX)': [2017],
            'Soletta Project': [2016],
            'Steel Bank Common Lisp': [2014],
            'Stony Brook University': [2017],
            'Stony Brook University Biomedical Informatics': [2016],
            'Stratosphere Project': [2014],
            'Subsurface': [2015, 2014],
            'Sugar Labs': [2017, 2016, 2015, 2014],
            'SuperTuxKart': [2014],
            'Sustainable Computing Research Group ( SCoRe )': [2017, 2016, 2015],
            'Swathanthra Malayalam Computing': [2014],
            'SymPy': [2017, 2016, 2014],
            'SyncDiff(erent)': [2014],
            'Systers': [2017, 2016, 2015, 2014],
            'TARDIS SN': [2015],
            'TARDIS-SN': [2016],
            'TEAMMATES @ National University of Singapore': [2017, 2016, 2015],
            'TEAMMATES Project @ National University of Singapore': [2014],
            'TYPO3 Association': [2014],
            'The Apertium Project': [2016],
            'The CGAL Project': [2017, 2014],
            'The Center for Connected Learning and Computer-Based Modeling': [2017, 2016],
            'The Concord Consortium': [2015, 2014],
            'The Eclipse Foundation': [2017, 2015, 2014],
            'The Fedora Project': [2015, 2014],
            'The FreeType Project': [2017],
            'The GNU Project': [2017],
            'The Honeynet Project': [2017, 2016, 2015],
            'The Java Pathfinder Team': [2017],
            'The Julia Language': [2017, 2016, 2014],
            'The LLVM Compiler Infrastructure': [2016],
            'The Libreswan Project': [2017],
            'The Linux Foundation': [2017, 2016, 2014],
            'The MacPorts Project': [2017, 2015, 2014],
            'The Monarch Initiative': [2016],
            'The NetBSD Foundation': [2017, 2016],
            'The OpenBSD Foundation': [2015, 2014],
            'The OpenCog Foundation': [2015, 2014],
            'The OpenStack Foundation': [2014],
            'The Perl Foundation': [2014],
            'The Privly Foundation': [2014],
            'The Processing Foundation': [2017, 2015, 2014],
            'The STE||AR Group': [2016, 2015, 2014],
            'The Tor Project': [2016],
            'The Tor Project and EFF': [2014],
            'The Visualization Toolkit': [2015],
            'The Wine Project': [2017, 2016, 2015, 2014],
            'The Wiselib': [2014],
            'The ns-3 Network Simulator Project': [2017, 2015, 2014],
            'The syslog-ng project': [2016, 2015, 2014],
            'ThinkUp': [2014],
            'Tiled': [2017],
            'TimVideos': [2017],
            'TimVideos.us': [2016, 2014],
            'Timelab Technologies Ltd.': [2016],
            'Tor': [2017],
            'Tox': [2015],
            'Tux4Kids': [2015],
            'Twitter': [2014],
            'UCSC Xena': [2017],
            'Unitex/GramLab': [2016],
            'University of Antwerp': [2017],
            'University of Nebraska - Helikar Lab': [2015],
            'Urban Energy Systems Laboratory': [2017, 2016],
            'Vert.x': [2016],
            'ViSP': [2017],
            'VideoLAN': [2017],
            'VideoLAN / VLMC Project': [2016],
            'Visualization Toolkit (VTK)': [2014],
            'WSO2': [2017, 2016, 2015, 2014],
            'Wayland': [2016],
            'Wikimedia': [2014],
            'Wikimedia Foundation': [2017, 2016, 2015],
            'WordPress': [2014],
            'WorldBrain - Verifying the Internet with Science': [2017],
            'WorldForge': [2014],
            'X.Org Foundation': [2017, 2016, 2015, 2014],
            'XBMC Foundation': [2017, 2015],
            'XMPP Standards Foundation': [2017, 2015],
            'XWiki': [2017, 2016],
            'Xapian Search Engine Library': [2017, 2016, 2014],
            'Xen Project': [2017, 2014],
            'Xiph.Org Foundation': [2015],
            'Zenodo': [2017],
            'Zulip': [2017],
            'Zulip Open Source Project': [2016],
            'aimacode': [2017, 2016],
            'an Anita Borg Institute Community': [2016],
            'an Anita Borg Institute community': [2017],
            'appleseed': [2014],
            'appleseedhq': [2017],
            'cBioPortal for Cancer Genomics': [2017, 2016],
            'coala': [2017],
            'coreboot': [2016, 2015, 2014],
            'dbpediaspotlight': [2016],
            'gRPC': [2016],
            'gnss-sdr': [2016],
            'haskell.org': [2015, 2014],
            'illumos.org': [2017],
            'jMonkeyEngine': [2014],
            'jQuery Foundation': [2016, 2015],
            'libvirt': [2017],
            'lmonade: scientific software distribution': [2015, 2014],
            'lowRISC': [2017, 2016, 2015],
            'mlpack': [2017],
            'mlpack: a scalable C++ machine learning library': [2016],
            'mlpack: scalable C++ machine learning library': [2014],
            'oVirt': [2017, 2014],
            'openSUSE': [2017, 2016, 2014],
            'ownCloud': [2017, 2016],
            'phpBB Forum Software': [2017, 2014],
            'phpMyAdmin': [2017, 2015, 2014],
            'radare': [2016],
            'radare2': [2017],
            'strace': [2017, 2016, 2015, 2014],
            'vitrivr': [2016],
            'wxWidgets': [2017, 2014]}
    once = {' Charles University in Prague': [2014],
            ' Department of Aerospace Engineering at the Polytechnic University of Milan': [2015],
            ' Finch': [2015],
            ' Inc.': [2014],
            ' SickKids Research Institute': [2014],
            ' Stony Brook University': [2015],
            ' and libpurple': [2015],
            'AOSSIE - Australian Open Source Software Innovation and Education': [2017],
            "AOSSIE - The Australian National University's Open-Source Software Innovation and Education": [2016],
            'AboutCode': [2017],
            'AerospaceResearch.Net': [2014],
            'AerospaceResearch.net': [2017],
            'Africa Soil Information Service': [2015],
            'Apertus Association': [2017],
            'ArchC': [2016],
            'Arches Project': [2014],
            'ArduPilot': [2017],
            'Association Tatoeba': [2014],
            'Babel': [2017],
            'Battle for Wesnoth': [2014],
            'Bazel': [2017],
            'BeagleBoard.org Foundation': [2017],
            'BeeWare Project': [2017],
            'Benetech': [2014],
            'Berkman Center for Internet and Society': [2016],
            'Berkman Klein Center for Internet and Society at Harvard University': [2017],
            'Bika Open Source LIMS Collective': [2015],
            'Bio4j': [2014],
            'BioJS': [2016],
            'BioJavaScript': [2014],
            'Bookie': [2014],
            'BumbleBee Autonomous Underwater Vehicle (BBAUV)': [2014],
            'CERN-HSF': [2017],
            'CLiPS': [2017],
            'CMU Sphinx': [2017],
            'CVXPY': [2016],
            'Cadasta': [2017],
            'Canadian Centre for Computational Genomics (C3G) - Montreal node': [2016],
            'Catrobat (formerly Catroid Project)': [2014],
            'Celluloid': [2016],
            'CentOS Project': [2015],
            'Centre for Computational Medicine': [2014],
            'Ceph Storage': [2015],
            'Cesium Community': [2015],
            'Checker Framework': [2017],
            'Cloud Native Computing Foundation (CNCF)': [2017],
            'CodeCombat': [2014],
            'CodeMirror': [2014],
            'Conversations.im': [2017],
            'Crypto Stick': [2014],
            'Crystal Space': [2014],
            'D Foundation': [2016],
            'DBpedia': [2017],
            'Department of Aerospace Science and Technology at Politecnico di Milano': [2016],
            'Department of Biomedical Informatics': [2015],
            'Distributed and Unified Numerics Environment (DUNE)': [2016],
            'Dr. Memory': [2014],
            'Eclipse Foundation': [2016],
            'Eclipse Vert.x': [2017],
            'Elm Software Foundation': [2017],
            'Emory University': [2016],
            'Encyclopedia of Life': [2015],
            'Environmental Data And Governance Initiative': [2017],
            'FOSDEM': [2017],
            'FOSDEM VZW': [2016],
            'Flowgrammable': [2014],
            'Foundation for Learning Equality': [2015],
            'Freenet Project Inc': [2014],
            'Frenetic': [2014],
            'Frescobaldi': [2017],
            'GENIVI Development Platform': [2017],
            'GPAC': [2016],
            'Gambit - Software Tools for Game Theory': [2016],
            'Gambit: Software Tools for Game Theory': [2014],
            'Ganglia': [2014],
            'Global Alliance for Genomics and Health': [2017],
            'Google Kubernetes': [2015],
            'Google Open Source Programs Office': [2014],
            'Grameen Foundation - MOTECH': [2014],
            'Groovy Community': [2014],
            'HPCC Systems®': [2015],
            'HelenOS group at Department of Distributed and Dependable Systems': [2014],
            'INCF': [2017],
            'IP-over-P2P Project': [2015],
            'Indic Project': [2016],
            'Intel Media and Audio for Linux': [2017],
            'Interactive Spaces': [2015],
            'International GeoGebra Institute': [2015],
            'Internet Archive': [2017],
            'Italian Mars Society': [2014],
            'Java Pathfinder Team': [2016],
            'Jenkins Project': [2016],
            'Joomla': [2017],
            'Joomla!': [2016],
            'Joomla! (Open Source Matters)': [2014],
            'K-9 Mail': [2017],
            'KolibriOS': [2016],
            'KolibriOS Project Team': [2014],
            'LEAP Encryption Access Project': [2014],
            'Laboratory for Cosmological Data Mining': [2014],
            'LibreHealth': [2017],
            'Libvirt': [2016],
            'Linaro': [2014],
            'Linux Trace Toolkit next generation project (LTTng)': [2014],
            'LuaRocks': [2017],
            'LyX – The Document Processor': [2014],
            'MEDES-IMPS': [2015],
            'MIT App Inventor': [2017],
            'McGill Space Institute': [2016],
            'Melange': [2014],
            'MetaBrainz Foundation': [2016],
            'Metasploit': [2017],
            'Microkernel devroom': [2017],
            'MinnowBoard Project': [2015],
            'ModSecurity': [2016],
            'Monkey Project': [2014],
            'NetSurf': [2014],
            'Netfilter Project': [2014],
            'Network Time Foundation': [2015],
            'OGDF - Open Graph Drawing Framework': [2014],
            'OSGeo': [2017],
            'OSGeo - The Open Source Geospatial Foundation': [2016],
            'OSU Open Source Lab': [2016],
            'OSv': [2014],
            'OncoBlocks': [2015],
            'Open Data Kit': [2017],
            'Open Education Resource Foundation': [2014],
            'Open Ephys': [2016],
            'Open Lighting Project': [2014],
            'Open Motion Planning Library': [2014],
            'Open States': [2017],
            'Open Technologies Alliance - GFOSS': [2017],
            'OpenWISP': [2017],
            'Openwall': [2015],
            'Orange – Data Mining Fruitful & Fun': [2016],
            'PEcAn Project': [2017],
            'PLASMA @ UMass': [2015],
            'PLASMA-UMass': [2016],
            'PMD': [2017],
            'PaGMO / PyKEP': [2015],
            'Pencil Code Foundation': [2015],
            'Peragro': [2016],
            'Pharo Consortium': [2017],
            'Pidgin': [2015],
            'Plan 9 from Bell Labs': [2014],
            'Point Cloud Library (PCL)': [2014],
            'Polly Labs': [2017],
            'Portable Native Client': [2015],
            'PostgreSQL': [2017],
            'Privly Foundation': [2015],
            'Project Tox': [2014],
            'Public Laboratory for Open Technology and Science': [2014],
            'Qubes OS': [2017],
            'RIOT': [2015],
            'Raxa': [2014],
            'Robocomp': [2016],
            'Rocket.Chat': [2017],
            'Rspamd': [2017],
            'Rspamd spam filtering system': [2015],
            'Ruby Science Foundation (SciRuby)': [2014],
            'STE||AR Group': [2017],
            'Sahana Software Foundation': [2014],
            'Saros': [2015],
            'Scaffold Hunter': [2014],
            'Scilab': [2017],
            'Software Freedom Conservancy': [2014],
            'Software Product Data Exchange (SPDX)': [2017],
            'Soletta Project': [2016],
            'Steel Bank Common Lisp': [2014],
            'Stony Brook University': [2017],
            'Stony Brook University Biomedical Informatics': [2016],
            'Stratosphere Project': [2014],
            'SuperTuxKart': [2014],
            'Swathanthra Malayalam Computing': [2014],
            'SyncDiff(erent)': [2014],
            'TARDIS SN': [2015],
            'TARDIS-SN': [2016],
            'TEAMMATES Project @ National University of Singapore': [2014],
            'TYPO3 Association': [2014],
            'The Apertium Project': [2016],
            'The FreeType Project': [2017],
            'The GNU Project': [2017],
            'The Java Pathfinder Team': [2017],
            'The LLVM Compiler Infrastructure': [2016],
            'The Libreswan Project': [2017],
            'The Monarch Initiative': [2016],
            'The OpenStack Foundation': [2014],
            'The Perl Foundation': [2014],
            'The Privly Foundation': [2014],
            'The Tor Project': [2016],
            'The Tor Project and EFF': [2014],
            'The Visualization Toolkit': [2015],
            'The Wiselib': [2014],
            'ThinkUp': [2014],
            'Tiled': [2017],
            'TimVideos': [2017],
            'Timelab Technologies Ltd.': [2016],
            'Tor': [2017],
            'Tox': [2015],
            'Tux4Kids': [2015],
            'Twitter': [2014],
            'UCSC Xena': [2017],
            'Unitex/GramLab': [2016],
            'University of Antwerp': [2017],
            'University of Nebraska - Helikar Lab': [2015],
            'Vert.x': [2016],
            'ViSP': [2017],
            'VideoLAN': [2017],
            'VideoLAN / VLMC Project': [2016],
            'Visualization Toolkit (VTK)': [2014],
            'Wayland': [2016],
            'Wikimedia': [2014],
            'WordPress': [2014],
            'WorldBrain - Verifying the Internet with Science': [2017],
            'WorldForge': [2014],
            'Xiph.Org Foundation': [2015],
            'Zenodo': [2017],
            'Zulip': [2017],
            'Zulip Open Source Project': [2016],
            'an Anita Borg Institute Community': [2016],
            'an Anita Borg Institute community': [2017],
            'appleseed': [2014],
            'appleseedhq': [2017],
            'coala': [2017],
            'dbpediaspotlight': [2016],
            'gRPC': [2016],
            'gnss-sdr': [2016],
            'illumos.org': [2017],
            'jMonkeyEngine': [2014],
            'libvirt': [2017],
            'mlpack': [2017],
            'mlpack: a scalable C++ machine learning library': [2016],
            'mlpack: scalable C++ machine learning library': [2014],
            'radare': [2016],
            'radare2': [2017],
            'vitrivr': [2016]}
    twice = {' Emory University': [2015, 2014],
             ' an Anita Borg Institute Community': [2015, 2014],
             'ASCEND': [2016, 2015],
             'Amahi': [2017, 2014],
             'Apertium': [2017, 2014],
             'BEAM Community': [2015, 2014],
             'Beam Community': [2017, 2016],
             'Buildbot': [2015, 2014],
             'CCExtractor Development': [2017, 2016],
             'CCExtractor development': [2015, 2014],
             'Catrobat': [2017, 2016],
             'Chapel': [2017, 2016],
             'Checkstyle': [2017, 2014],
             'Classical Language Toolkit': [2017, 2016],
             'Computational Biology @ University of Nebraska-Lincoln': [2017, 2016],
             'Computational Science and Engineering at TU Wien': [2016, 2014],
             'DBpedia & DBpedia Spotlight': [2015, 2014],
             'Discourse': [2017, 2016],
             'Empa': [2017, 2016],
             'Fedora Project': [2017, 2016],
             'Free and Open Source Silicon Foundation': [2017, 2016],
             'GCC - GNU Compiler Collection': [2015, 2014],
             'GNU Mailman': [2016, 2015],
             'Genes': [2017, 2016],
             'Genomes and Variation': [2017, 2016],
             'GitHub': [2016, 2015],
             'Global Alliance for Genomics & Health': [2016, 2015],
             'Green Navigation': [2017, 2016],
             'Haiku': [2017, 2014],
             'Health Information Systems Programme': [2016, 2014],
             'Homebrew': [2017, 2016],
             'Inclusive Design Institute': [2016, 2014],
             'JSK Robotics Laboratory': [2017, 2016],
             'JdeRobot - Universidad Rey Juan Carlos': [2017, 2015],
             'Jitsi': [2017, 2014],
             'MIT Media Lab': [2016, 2015],
             'Matrix.org': [2017, 2016],
             'Mobile Robot Programming Toolkit (MRPT)': [2017, 2016],
             'MovingBlocks': [2017, 2016],
             'Netfilter project': [2017, 2016],
             'OSGeo - Open Source Geospatial Foundation': [2015, 2014],
             'OWASP Foundation': [2016, 2014],
             'Open Chemistry': [2017, 2016],
             'Open Detection': [2017, 2016],
             'Open Genome Informatics': [2017, 2016],
             'Open Source Computer Vision Library (OpenCV)': [2015, 2014],
             'OpenAstronomy': [2017, 2016],
             'OpenCV': [2017, 2016],
             'Oppia Foundation': [2017, 2016],
             'Oregon State University Open Source Lab (OSUOSL)': [2015, 2014],
             'PRISM Model Checker': [2016, 2014],
             'Performance Co-Pilot': [2017, 2016],
             'Physical Web Project': [2017, 2016],
             'PostgreSQL Project': [2015, 2014],
             'Public Lab': [2017, 2016],
             'R Project for Statistical Computing': [2015, 2014],
             'R project for statistical computing': [2017, 2016],
             'ReactOS': [2017, 2016],
             'RoboComp': [2017, 2015],
             'RouteFlow': [2015, 2014],
             'Ruby': [2016, 2015],
             'Samba': [2017, 2014],
             'Scala': [2017, 2016],
             'Scala Team': [2015, 2014],
             'Scilab Enterprises': [2016, 2015],
             'Subsurface': [2015, 2014],
             'The CGAL Project': [2017, 2014],
             'The Center for Connected Learning and Computer-Based Modeling': [2017, 2016],
             'The Concord Consortium': [2015, 2014],
             'The Fedora Project': [2015, 2014],
             'The NetBSD Foundation': [2017, 2016],
             'The OpenBSD Foundation': [2015, 2014],
             'The OpenCog Foundation': [2015, 2014],
             'TimVideos.us': [2016, 2014],
             'Urban Energy Systems Laboratory': [2017, 2016],
             'XBMC Foundation': [2017, 2015],
             'XMPP Standards Foundation': [2017, 2015],
             'XWiki': [2017, 2016],
             'Xen Project': [2017, 2014],
             'aimacode': [2017, 2016],
             'cBioPortal for Cancer Genomics': [2017, 2016],
             'haskell.org': [2015, 2014],
             'jQuery Foundation': [2016, 2015],
             'lmonade: scientific software distribution': [2015, 2014],
             'oVirt': [2017, 2014],
             'ownCloud': [2017, 2016],
             'phpBB Forum Software': [2017, 2014],
             'wxWidgets': [2017, 2014]}
    thrice = {'BeagleBoard.org': [2016, 2015, 2014],
              'Blender Foundation': [2017, 2016, 2014],
              'Boost C++ Libraries': [2017, 2015, 2014],
              'Boston University / XIA': [2017, 2016, 2015],
              'BuildmLearn': [2016, 2015, 2014],
              'CERN SFT': [2016, 2015, 2014],
              'Ceph': [2017, 2016, 2014],
              'CiviCRM': [2016, 2015, 2014],
              'Clojure': [2017, 2015, 2014],
              'CloudCV': [2017, 2016, 2015],
              'Debian Project': [2016, 2015, 2014],
              'Django Software Foundation': [2017, 2016, 2014],
              'FFmpeg': [2017, 2016, 2015],
              'Freifunk': [2017, 2016, 2014],
              'GNSS-SDR': [2017, 2015, 2014],
              'GNU Octave': [2017, 2016, 2014],
              'GNU Project': [2016, 2015, 2014],
              'GNU Radio': [2017, 2016, 2014],
              'Ganeti': [2016, 2015, 2014],
              'Gentoo Foundation': [2017, 2016, 2014],
              'Inkscape': [2017, 2016, 2014],
              'Institute for Artificial Intelligence': [2017, 2015, 2014],
              'International Neuroinformatics Coordinating Facility': [2016, 2015, 2014],
              'LLVM Compiler Infrastructure': [2017, 2015, 2014],
              'MBDyn': [2017, 2016, 2015],
              'MetaBrainz Foundation Inc.': [2017, 2015, 2014],
              'Mifos Initiative': [2017, 2016, 2014],
              'Mixxx DJ Software': [2017, 2016, 2014],
              'Mono Project': [2017, 2015, 2014],
              'Mozilla': [2017, 2016, 2014],
              'MuseScore': [2017, 2016, 2014],
              'National Resource for Network Biology (NRNB)': [2017, 2016, 2014],
              'NumFOCUS': [2017, 2016, 2015],
              'Open Bioinformatics Foundation': [2017, 2016, 2014],
              'Open Source Robotics Foundation': [2016, 2015, 2014],
              'OpenKeychain (OpenPGP for Android)': [2016, 2015, 2014],
              'OpenStreetMap': [2017, 2016, 2015],
              'P2PSP.org': [2017, 2016, 2015],
              'Plone Foundation': [2017, 2016, 2014],
              'Red Hen Lab': [2017, 2016, 2015],
              'Ruby Science Foundation': [2017, 2016, 2015],
              'Ruby on Rails': [2017, 2015, 2014],
              'ScummVM': [2017, 2016, 2014],
              'Shogun Machine Learning Toolbox': [2017, 2016, 2014],
              'Sigmah': [2017, 2016, 2014],
              'Sustainable Computing Research Group ( SCoRe )': [2017, 2016, 2015],
              'SymPy': [2017, 2016, 2014],
              'TEAMMATES @ National University of Singapore': [2017, 2016, 2015],
              'The Eclipse Foundation': [2017, 2015, 2014],
              'The Honeynet Project': [2017, 2016, 2015],
              'The Julia Language': [2017, 2016, 2014],
              'The Linux Foundation': [2017, 2016, 2014],
              'The MacPorts Project': [2017, 2015, 2014],
              'The Processing Foundation': [2017, 2015, 2014],
              'The STE||AR Group': [2016, 2015, 2014],
              'The ns-3 Network Simulator Project': [2017, 2015, 2014],
              'The syslog-ng project': [2016, 2015, 2014],
              'Wikimedia Foundation': [2017, 2016, 2015],
              'Xapian Search Engine Library': [2017, 2016, 2014],
              'coreboot': [2016, 2015, 2014],
              'lowRISC': [2017, 2016, 2015],
              'openSUSE': [2017, 2016, 2014],
              'phpMyAdmin': [2017, 2015, 2014]}
    four_times = {'52°North Initiative for Geospatial Open Source Software GmbH': [2017, 2016, 2015, 2014],
                  'Apache Software Foundation': [2017, 2016, 2015, 2014],
                  'BRL-CAD': [2017, 2016, 2015, 2014],
                  'Biomedical Informatics': [2017, 2016, 2015, 2014],
                  'Copyleft Games': [2017, 2016, 2015, 2014],
                  'Drupal': [2017, 2016, 2015, 2014],
                  'FOSSASIA': [2017, 2016, 2015, 2014],
                  'FreeBSD': [2017, 2016, 2015, 2014],
                  'GNOME': [2017, 2016, 2015, 2014],
                  'Git': [2017, 2016, 2015, 2014],
                  'JBoss Community': [2017, 2016, 2015, 2014],
                  'KDE': [2017, 2016, 2015, 2014],
                  'LabLua': [2017, 2016, 2015, 2014],
                  'LibreOffice': [2017, 2016, 2015, 2014],
                  'Liquid Galaxy Project': [2017, 2016, 2015, 2014],
                  'MariaDB': [2017, 2016, 2015, 2014],
                  'Moodle': [2017, 2016, 2015, 2014],
                  'Nmap Security Scanner': [2017, 2016, 2015, 2014],
                  'OpenMRS': [2017, 2016, 2015, 2014],
                  'Portland State University': [2017, 2016, 2015, 2014],
                  'Python Software Foundation': [2017, 2016, 2015, 2014],
                  'QEMU': [2017, 2016, 2015, 2014],
                  'RTEMS Project': [2017, 2016, 2015, 2014],
                  'Sage Mathematical Software System': [2017, 2016, 2015, 2014],
                  'Sugar Labs': [2017, 2016, 2015, 2014],
                  'Systers': [2017, 2016, 2015, 2014],
                  'The Wine Project': [2017, 2016, 2015, 2014],
                  'WSO2': [2017, 2016, 2015, 2014],
                  'X.Org Foundation': [2017, 2016, 2015, 2014],
                  'strace': [2017, 2016, 2015, 2014]}
    for i in orgs_2014:
        print(i)
